### ISSUE TITLE
Not able to run

### ISSUE THREAD

**Issue by sumairirshad** [void-type/Time_Clock_Web_App_and_API#1]
Your project is not able to run seems like there  is lot of dynamic errors can you update with the working one or you deliberately did that?

**Comment by void-type** [comment]
Hi. It was not deliberate. I think the issue was that the "Time card model" project would not open in newer versions of Visual Studio. I dropped the project and cleaned up the code.
I can compile and run the project in VS2017 as of commit cfe95fc6.
